---
- name: Template Looping
  hosts: localhost

   vars: 
     csr-1: {
       "CSR-1": {
            "hostname": "CSR-1", 
            "username": "admin", 
            "password": "admin", 
            "vlans": [100, 200, 300],
            "l3_vlan_interfaces": True,
            "vlan_interfaces": [
                {"int_num": "100", "ip": "192.168.10.1"},
                {"int_num": "200", "ip": "192.168.20.1"},
                {"int_num": "300", "ip": "192.168.30.1"}
            ],
            "netflow_enable": True    
        }
    }
  tasks:
    - name: create router configuration files
      template: 
        src=./ios.j2
        dest=./{{ item.key }}.conf
      with_dict: "{{ csr-1 }}"
